### ISSUE TITLE
lemonmon - `TokenUtils.getDecimals()` is not supporting tokens with more than 18 decimals

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#101]
lemonmon

medium

# `TokenUtils.getDecimals()` is not supporting tokens with more than 18 decimals

## Summary

`TokenUtils.getDecimals()` is not supporting tokens with decimals bigger than 18. Whenever this function gets called with a token that has more than 18 decimals, there will be a revert triggered. Thus, certain vaults can't be created with tokens that have more than 18 decimals.

## Vulnerability Detail

Whenever `TokenUtils.getDecimals()` is used with a token that has more than 18 decimals a revert will be triggered on line 14 in TokenUtils.sol.

According to the [contest page](https://audits.sherlock.xyz/contests/119) any ERC20 tokens should be supported.

> Which ERC20 tokens do you expect will interact with the smart contracts? <br>
> any

`TokenUtils.getDecimals()` is used by:

- `CrossCurrencyVault.initialize()` to set up `LEND_DECIMALS` and `BORROW_DECIMALS` (line 86-87 CrossCurrencyVault.sol) for the lend and borrow tokens.
- `BalancerComposableAuraVault` and `BalancerWeightedAuraVault` constructors to set up the decimals for the tokens (line 98-102 BalancerPoolMixin.sol)

## Impact

The Notional protocol is not compatible with tokens that have more than 18 decimals. Vaults like the `CrossCurrencyVault`, `BalancerComposableAuraVault`, `BalancerWeightedAuraVault` don't support tokens with more than 18 decimals as shown in the details above.

## Code Snippet

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/utils/TokenUtils.sol#L11-L14

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/balancer/mixins/BalancerPoolMixin.sol#L98-L102

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L86-L87

## Tool used

Manual Review

## Recommendation

Since any ERC20 tokens are supposed to be supported, consider supporting tokens with more than 18 decimals by adjusting the `TokenUtils.getDecimals()` function to not revert when a token has more than 18 decimals.

**Comment by jeffywu** [comment]
This is by design and furthermore, I do not believe there are any tokens with more than 18 decimals worth listing.

**Comment by nevillehuang** [comment]
> This is by design and furthermore, I do not believe there are any tokens with more than 18 decimals worth listing.

I think I will maintain medium severity since in the contest details it is stated that any tokens are deemed to be supported, and I believe notional will definitely be interested if in the future if there is any tokens more than 18 decimals worth listing.

**Comment by nevillehuang** [comment]
See additional comment [here](https://github.com/sherlock-audit/2023-10-notional-judging/issues/70#issuecomment-1836843782).

**Comment by 0xRizwan** [comment]
@nevillehuang 

I think @jeffywu is correct here. [This](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/utils/TokenUtils.sol#L14) check explicitely checks for tokens decimals to be `decimals <=18`. If the contracts has to support >18 decimal tokens then the require check wouldn't be there in first place. I think its a well intended design by project team.

Please correct me if i am missing anything.

**Comment by VagnerAndrei26** [comment]
Escalate 
I think this issue should not be valid in reality, there are some design choices that developers intend to use for their benefits, even if it stated that any ERC20 tokens should be able to interact with the protocol, clearly by this check 
https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/utils/TokenUtils.sol#L14 it intends to work only with 18 decimals or less tokens. This does not have any real impact on the protocol and should be categorized as a low/informational at most.

**Comment by sherlock-admin2** [comment]
> Escalate 
> I think this issue should not be valid in reality, there are some design choices that developers intend to use for their benefits, even if it stated that any ERC20 tokens should be able to interact with the protocol, clearly by this check 
> https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/utils/TokenUtils.sol#L14 it intends to work only with 18 decimals or less tokens. This does not have any real impact on the protocol and should be categorized as a low/informational at most.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by lemonmon1984** [comment]
Even if the protocol's implementation only supports ERC20 tokens with up to 18 decimals doesn't change the fact that the contest page stated that any ERC20 tokens are supposed to be supported. Also, clarity and explicit specs should take precedent over implicit intentions; this is especially important for the work of Watsons; and also for 3rd party developers when they integrate with Notional, they may not read all the implementation source code but only rely on the docs and specs.

About the impact:

Similar to this issue https://github.com/sherlock-audit/2023-10-notional-judging/issues/70#issuecomment-1830989553 supporting tokens with more than 18 decimals may be potentially profitable for the protocol. For example there are ERC20 tokens with more than 18 decimals:

- NEAR has 24 decimals
- YAM-V2 has 24 decimals

Furthermore, in the future there might be even more tokens with more than 18 decimals which the protocol may want to support. This may also impact the profitability and composability of the protocol.

**Comment by xiaoming9090** [comment]
Per the Curve documentation (https://resources.curve.fi/factory-pools/pool-factory/), tokens with more than 18 decimals are not supported.

This discord message from someone from Balancer Lab (https://discord.com/channels/638460494168064021/638529669330894868/848957926777684049) mentioned that only tokens with 6-18 decimals are supported. If we review the internal codebase of Balancer pool, within the [`_computeScalingFactor`](https://github.com/balancer/balancer-v2-monorepo/blob/f45076067b68b27ea023632e69349e3051746cd4/pkg/pool-utils/contracts/BasePool.sol#L492) function, it explicitly stated that tokens with more than 18 decimals are not supported.

There won't be a case where there will be a Curve or Balancer pool that consists of a token with more than 18 decimals. Thus, there is no need for the Leverage Vault's contracts to support tokens with 18 decimals since such a pool does not exist in Curve and Balancer in the first place.

**Comment by nevillehuang** [comment]
Agree with @xiaoming9090, additionally this tokens could also be looked as "weird" ERC20 tokens, and based on this comment [here](https://github.com/sherlock-audit/2023-10-notional-judging/issues/102#issuecomment-1842990023), suggest to invalidate issue.

**Comment by Czar102** [comment]
Agree with points above. Planning to accept the escalation and invalidate the issue.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [VagnerAndrei26](https://github.com/sherlock-audit/2023-10-notional-judging/issues/101/#issuecomment-1839411800): accepted
