### ISSUE TITLE
Jaraxxus - UUPSUpgradeable is not initialized

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#108]
Jaraxxus

medium

# UUPSUpgradeable is not initialized

## Summary

UUPSUpgradeable does not call the `__UUPSUpgradeable_init()` function, which it should.

## Vulnerability Detail

`__UUPSUpgradeable_init()` is not called during initialization in SingleSidedLPVaultBase.

SingleSidedLPVaultBase inherits UUPSUpgradeable,

```solidity
abstract contract SingleSidedLPVaultBase is BaseStrategyVault, UUPSUpgradeable, ISingleSidedLPStrategyVault {
```

but does not call `__UUPSUpgradeable_init()`

```solidity
    function initialize(InitParams calldata params) external override initializer onlyNotionalOwner {
        // Initialize the base vault
        __INIT_VAULT(params.name, params.borrowCurrencyId);

        // Settings are validated in setStrategyVaultSettings
        VaultStorage.setStrategyVaultSettings(params.settings);

        _initialApproveTokens();
    }
```

## Impact

Although `_UUPSUpgradeable_init()` is an empty function, best practice from OpenZeppelin team, 

> __UUPSUpgradeable_init is an empty function actually. The Wizard includes it because it follows our general recommendation which is to include all inits for all parents, so as not to require checking whether a function is empty or not, and to future-proof for the possibility that we add initialization logic at some point. So I've updated the code to reflect this recommendation.

https://forum.openzeppelin.com/t/uups-proxies-tutorial-solidity-javascript/7786/29

## Code Snippet

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L173-L181

## Tool used

Manual Review

## Recommendation

Call `__UUPSUpgradeable_init()` when initializing.

**Comment by nevillehuang** [comment]
Invalid, informational finding that is pointing to best practices with no additional impact on protocol
