### ISSUE TITLE
shealtielanz - If the lend token is eth, redeemfCash will most likely revert

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#109]
shealtielanz

false

# If the lend token is eth, redeemfCash will most likely revert

## Vulnerability Detail
In the scenario the lendtoken is eth, redeemfCash() calls wfCash.redeem() before checking if the lendtoken is eth and before the check to eth is done the function will revert it it doesn’t have proportional vault shares in fcash.
## Impact

_redeemFromNotional() and _convertVaultSharesToPrimeMaturity() will revert on the call to _redeemfCash() in some scenarios when the lendtoken is eth
## Code Snippet
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L278
## Tool used

Manual Review

## Recommendation
check if the lendtoken is eth before the call to wfCash.redeem() and put in an if else statement.

**Comment by nevillehuang** [comment]
Invalid, if underlying token is ETH, `LEND_ETH` will be true as seen [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L83) and thus `isETH` will be true, so wETH will be withdrawn as expected when `_redeemfCash()` is invoked and will not revert.
