### ISSUE TITLE
shealtielanz - An attacker can brick redemption from notional and settlements in crossCurrency vault

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#110]
shealtielanz

high

# An attacker can brick redemption from notional and settlements in crossCurrency vault

## Summary
In  `_convertVaultSharesToPrimeMaturity()` and `_redeemFromNotional()` in crossCurrency vault, They both share similar logic [1](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L244), [2](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L273) where they calculate the balance before and then call `redeemfCash()` then calculates the balance after, which it then uses to get the amount to be traded(for the `_redeemFromNotional()`) or the amount to be deposit to prime cash(for the `_convertVaultSharesToPrimeMaturity(`)).
The issue is that `redeemfCash()` under the hood calls `wfCash::redeem()`,

https://github.com/notional-finance/wrapped-fcash/pull/12/files#diff-7c9f6e4700cce75c3c2abb4902f45f7398dcac73135a605b59825b26de7d6af0

 an attacker can call this on behalf of the vault(via frontrunning) and when calculating balance After minus the balance before the amount would be zero, thereby trading or depositing zero amount during redeeming from notional or converting vault shares to prime maturity.
## Impact
Here the functionality of the two functions would be bricked when redeeming and during settlement.
## Code Snippet
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L280
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L270
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L235
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L244
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L273
## Tool used

Manual Review

## Recommendation
Create a means of tracking the contract’s balance internally to ensure against this.

**Comment by nevillehuang** [comment]
Invalid, not possible since `msg.sender` is used in `wfCashLogic.redeem()`, so cannot redeem in place of vault as seen [here](https://github.com/notional-finance/wrapped-fcash/blob/master/contracts/wfCashLogic.sol#L168)
