### ISSUE TITLE
jah - wrong logic when swaping  a  token

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#114]
jah

medium

# wrong logic when swaping  a  token

## Summary
wrong logic when trying to swap the token
## Vulnerability Detail
in tradingUtils line 158 it says that if the user  want  to receive weth but instead received ETH it will try first check if the new balance of buy is greater  than  the pre buy balance if it is it will try to subtract the subtract the pre buy balance from the the new balance and it will try to swap it into weth or eth but the thing  is that lets say a user want to swap eth into weth but as the comment say they might receive the buy token which is ETH so if they try to swap 10 ETH into WETH but received ETH but what they are going to receive will not be   greater than  the prebalance of eth it will be equal to 10 ETH which is the prebalcnce  so the if statement will not be excuted 
## Impact
wrong logic
## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingUtils.sol#L157
## Tool used

Manual Review

## Recommendation
try to subtract the amount from the prebalance and try to check with that

**Comment by nevillehuang** [comment]
Invalid, in addition to lack of proof, this issue is extremely hard to follow so I am unsure what exactly the issue is pointing to.
