### ISSUE TITLE
ginlee - No validation for primaryIndex may lead to unexpected amountOut for user

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#16]
ginlee

medium

# No validation for primaryIndex may lead to unexpected amountOut for user

## Vulnerability Detail
Since executeRedemptionTrades is a public function, anyone can call with random primaryIndex
```solidity
 address primaryToken = address(tokens[primaryIndex])
```
if primaryIndex is larger than tokens.length, instead of reverting, primaryToken will be set to 0 address， it will be passed as fourth param in _executeDynamicSlippageTradeExactIn
```solidity
if (exitBalances[i] > 0) {
                (/* */, uint256 amountBought) = _executeDynamicSlippageTradeExactIn(
                    Deployments.TRADING_MODULE, t, address(tokens[i]), primaryToken, exitBalances[i]
                );
```
In _executeDynamicSlippageTradeExactIn, fourth param is buyToken and is used to calculate trade, which may lead to unexpected amountOut for user
```solidity
 function _executeDynamicSlippageTradeExactIn(
        ITradingModule tradingModule,
        TradeParams memory params,
        address sellToken,
        address buyToken,
        uint256 amount
    ) internal returns (uint256 amountSold, uint256 amountBought)
```
## Impact
If the transaction is executed in some way with the buyToken as a zero address, funds may be directed to an unpredictable destination, or the transaction logic may operate in an unintended manner.

## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L59-L87
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L119-L147

## Tool used
Manual Review

## Recommendation
It is necessary to ensure that primaryIndex does not exceed the bounds of the tokens array
```solidity
require(primaryIndex < tokens.length, "primaryIndex out of bounds");
```

**Comment by nevillehuang** [comment]
Invalid, this will revert with out of bounds since primary index will exceed acceptable index to retrieve data from `tokens` array
