### ISSUE TITLE
dany.armstrong90 - CrossCurrencyVault.convertStrategyToUnderlying: The return value is miscalculated.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#24]
dany.armstrong90

high

# CrossCurrencyVault.convertStrategyToUnderlying: The return value is miscalculated.

## Summary
In `CrossCurrencyVault.sol#convertStrategyToUnderlying` function, when calculating the `underlyingValue` value, decimal of rate instead of  precision is used.
As a result, the return value `underlyingValue` has become enormously large, so that Notional misjudges that vault user is fully collatoralized, and bad debt is generated.

## Vulnerability Detail
The `CrossCurrencyVault.sol#convertStrategyToUnderlying` function is as follows.
```solidity
File: CrossCurrencyVault.sol
107:     function convertStrategyToUnderlying(
108:         address /* account */,
109:         uint256 vaultShares,
110:         uint256 maturity
111:     ) public override view returns (int256 underlyingValue) {
112:         int256 pvExternalUnderlying;
...
128: 
129:         // Returns the oracle price between the lend and borrow tokens.
130:         IERC20 underlyingToken = _underlyingToken();
131:         (int256 rate, int256 rateDecimals) = TRADING_MODULE.getOraclePrice(
132:             address(LEND_UNDERLYING_TOKEN), address(underlyingToken)
133:         );
134:         int256 borrowPrecision = int256(10**BORROW_DECIMALS);
135:         int256 lendPrecision = int256(10**LEND_DECIMALS);
136: 
137:         // Convert this back to the borrow currency, external precision
138:         // (pv (lend decimals) * borrowDecimals * rate) / (rateDecimals * lendDecimals)
139:         return (pvExternalUnderlying * borrowPrecision * rate) /
140:             (rateDecimals * lendPrecision);
141:     }
```
In line 139, rate is divided by `rateDecimal` instead of `ratePrecision = 10 ** rateDecimal`.
For example, if `rateDecimal == 10`, the return value `underlyingValue` is amplified by a factor of `10 ** rateDecimal / rateDecimal == 1e9`.
Due to `SingleSidedLPVaultBase.sol#L304-L305`, this function is used to check the collatoralization rate of vault user by Notional.
Thus Notional misjudges that vault user is fully collatoralized and bad debt is generated.

## Impact
Notional misjudges that vault user is fully collatoralized and bad debt is generated.

## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L140

## Tool used

Manual Review

## Recommendation
Modify the code `CrossCurrencyVault.sol#L139-L140` as follows.
```solidity
        return (pvExternalUnderlying * borrowPrecision * rate) /
            (10 ** rateDecimals * lendPrecision);
```

**Comment by nevillehuang** [comment]
Invalid, rate decimals hard coded to correct rate decimals which is assigned to 1e18 (10 ** 18)  in constructor of `TradingModule.sol` [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/trading/TradingModule.sol#L38) , and retrieved in `getOraclePrice()` [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/trading/TradingModule.sol#L260)
