### ISSUE TITLE
shealtielanz - TradingUtils._executeTrade() will leak ETH to WETH

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#38]
shealtielanz

high

# TradingUtils._executeTrade() will leak ETH to WETH

## Summary
If sellToken is `ETH`, and using Uniswap for the dex, and it is exact out trade, too much is deposited to the `WETH` and does not withdraw the excess amount. It will give wrong `amountSold` value as well as accounting error.
## Vulnerability Detail
trade.sellToken is ETH and using Uniswap as dex, `WETH` should be used instead of `ETH` as Uniswap does not support `ETH`. There for `TradingUtils` wraps the `ETH` to `WETH` before trading.

If the trade would be exact out, the amount trade.limit will be deposited to `WETH`  instead of the trade.amount. However, because it is exact out, not all `ETH` deposited will be traded. In the current implementation, there is no logic to recover the excess deposit.

As the `TradingUtils::_executeInternal`, which uses the `TradingUtils::_executeTrade` will calculate the `amountSold` based on the balance of `ETH`, it will return the trade.limit as the `amountSold`, thus resulting in accounting error.

## Impact
`amountSold` will reflect not the amount really sold, rather the trade.limit. It is unclear whether the excess amount of `ETH`, which is deposited for `WETH` can be recovered.
## Code Snippet
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingUtils.sol#L143C1-L151C10
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingUtils.sol#L28C1-L63C6
## Tool used

Manual Review, exactly same issue was found in the notional past audit but the fix isn't implemented in this current codebase, 
link [here](https://github.com/sherlock-audit/2022-09-notional-judging/issues/98)

## Recommendation
In the `_executeTrade`, if the sellToken is `ETH` and it is exact out trade, recover excess deposit

**Comment by nevillehuang** [comment]
Out of Scope, issue does not link to how an inscope contract can be affected by finding found in an out of scope contract, and it is not the judges responsibility to help watson do so. Additionally, issue is already fixed in previous contest as seen [here](https://github.com/notional-finance/leveraged-vaults/commit/251e4155c919730127d5f13aba285e5130581449).

**Comment by shealtielanz** [comment]
Escalate


concerning 
> Out of Scope, issue does not link to how an inscope contract can be affected by finding found in an out of scope contract, and it is not the judges responsibility to help watson do so. 


_executeTrade() in tradeUtils is used in `_executeInternal` function in the contract and both functions are use in TradingModule and is called by TradeHandler which is used 
- StrategyUtils [link here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L109) [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L144) [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L175)
- BaseStrategyVault  [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/BaseStrategyVault.sol#L124) 
- CrossCurrencyVault [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L184) [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L252)

 This contracts are clearly in scope and under the hood make use of  [_executeTrade()](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/trading/TradingUtils.sol#L143C1-L151C10) in TradingUtils for all trades.

concerning 
> Additionally, issue is already fixed in previous contest as seen [here](https://github.com/notional-finance/leveraged-vaults/commit/251e4155c919730127d5f13aba285e5130581449).


the [TradingUtils](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/trading/TradingUtils.sol#L11C1-L11C23) contract used for this notional update is the library with the bug not the one you referenced.

**whenever used for this trades ETH will be leaked to WETH as described in the report.**

This finding is valid.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> 
> concerning 
> > Out of Scope, issue does not link to how an inscope contract can be affected by finding found in an out of scope contract, and it is not the judges responsibility to help watson do so. 
> 
> 
> _executeTrade() in tradeUtils is used in `_executeInternal` function in the contract and both functions are use in TradingModule and is called by TradeHandler which is used 
> - StrategyUtils [link here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L109) [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L144) [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L175)
> - BaseStrategyVault  [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/BaseStrategyVault.sol#L124) 
> - CrossCurrencyVault [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L184) [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L252)
> 
>  This contracts are clearly in scope and under the hood make use of  [_executeTrade()](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/trading/TradingUtils.sol#L143C1-L151C10) in TradingUtils for all trades.
> 
> concerning 
> > Additionally, issue is already fixed in previous contest as seen [here](https://github.com/notional-finance/leveraged-vaults/commit/251e4155c919730127d5f13aba285e5130581449).
> 
> 
> the [TradingUtils](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/trading/TradingUtils.sol#L11C1-L11C23) contract used for this notional update is the library with the bug not the one you referenced.
> 
> **whenever used for this trades ETH will be leaked to WETH as described in the report.**
> 
> This finding is valid.
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@shealtielanz 

While the contracts in scope uses these functions, your submission still lack description of how it will impact contracts in scope. Additionally, unless I am missing something, the correct `TradingUtils.sol` contract is used that has already implemented the fix based on the previous audit contest.

**Comment by shealtielanz** [comment]
**Concerning**
> While the contracts in scope uses these functions, your submission still lack description of how it will impact contracts in scope. 


**According to the report:**
> amountSold will reflect not the amount really sold, rather the trade.limit. It is unclear whether the excess amount of ETH, which is deposited for WETH can be recovered.

The `amountSold` will be incorrect causing account issues when joining `curve` or `balancer` pools, where the correct amount of `WETH` will not be accounted for in the vault and result in a loss of assets, and rewards gotten from the pools.

**Flow Instance**
`SingleSidedLPVaultBase.sol._depositFromNotional()` -> `StrategyUtils.executeDepositTrades()` -> `StrategyUtils._executeDynamicSlippageTradeExactIn()` -> `TradeHandler._executeTradeWithDynamicSlippage()` -> `TradingModule.executeTradeWithDynamicSlippage()` -> ` TradingUtils._executeInternal()` -> `TradingUtils._executeTrade()`

**On the call to [`_depositFromNotional()`](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L191C1-L224C6):**   the `WETH` or `ETH` trade is executed using `StrategyUtils.executeDepositTrades()` then the `amounts` gotten will be used to `_joinPoolAndStake()` where it generates the `lpTokens` to `_mintVaultShares()`.
- *Read The inline comments*
```solidity
    function _depositFromNotional(
        address /* account */, uint256 deposit, uint256 /* maturity */, bytes calldata data
    ) internal override whenNotLocked returns (uint256 vaultSharesMinted) {
        // Short circuit any zero deposit amounts
        if (deposit == 0) return 0;

        DepositParams memory params = abi.decode(data, (DepositParams));
        uint256[] memory amounts = new uint256[](NUM_TOKENS());
        amounts[PRIMARY_INDEX()] = deposit;

        // If depositTrades are specified, then parts of the initial deposit are traded
        // for corresponding amounts of the other pool tokens via external exchanges. If
        // these amounts are not specified then the pool will just be joined single sided.
        // Deposit trades are not automatically enabled on vaults since the trading module
        // requires explicit permission for every token that can be sold by an address.
        if (params.depositTrades.length > 0) {
            (IERC20[] memory tokens, /* */) = TOKENS();
            // This is an external library call so the memory location of amounts is
            // different before and after the call.
    //@audit incorrect amount will be calculated for the amount of `ETH` sent to be sold to the `DEX`
     @>       amounts = StrategyUtils.executeDepositTrades(
                tokens,
                amounts,
                params.depositTrades,
                PRIMARY_INDEX()
            );
        }
   //@audit incorrect lpTokens calculated for the amounts
  @>      uint256 lpTokens = _joinPoolAndStake(amounts, params.minPoolClaim);
   //@audit incorrect amount of shares will be minted as the execess `ETH` deposited  wasn't accounted for.
     @>   return _mintVaultShares(lpTokens);
    }
```
**You can the issue in [`executeDepositTrades()`](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L50) :**
- *Read Inline comments*
```solidity
    /// @notice Trades the amount of primary token into other secondary tokens prior
    /// to entering a pool.
    function executeDepositTrades(
        IERC20[] memory tokens,
        uint256[] memory amounts,
        DepositTradeParams[] memory depositTrades,
        uint256 primaryIndex
    ) external returns (uint256[] memory) {
        address primaryToken = address(tokens[primaryIndex]);

        for (uint256 i; i < amounts.length; i++) {
            if (i == primaryIndex) continue;
            DepositTradeParams memory t = depositTrades[i];
            // Do not allow ZERO_EX trading in this method since we cannot validate
            // the arbitrary exchange data.
            if (DexId(t.tradeParams.dexId) == DexId.ZERO_EX) revert Errors.InvalidDexId(uint256(DexId.ZERO_EX));

            if (t.tradeAmount > 0) {
                // Always selling the primaryToken and buying the secondary token.
   //@audit amount of `WETH` and sold to the `DEX` doesn't reflect the actual  `ETH` sent 
                (uint256 amountSold, uint256 amountBought) = _executeDynamicSlippageTradeExactIn(
                    Deployments.TRADING_MODULE, t.tradeParams, primaryToken, address(tokens[i]), t.tradeAmount
                );

                amounts[i] = amountBought;
                // Will revert on underflow if over-selling the primary borrowed
   //@audit that incorrect amount of `WETH` sold will be subtracted from the primary Index.
                amounts[primaryIndex] -= amountSold;
            }
        }

        return amounts;
    }
```
And there is no way to ever recover the excess `ETH` that was wrapped to `WETH`.
- `NOTE` by Incorrect I mean, the unaccounted `ETH`  wrapped to `WETH` as the excess amount is un retrievable.

**Concerning**
>  unless I am missing something, the correct TradingUtils.sol contract is used that has already implemented the fix based on the previous audit contest.

**The `TradingUtils.sol` Library in the repo given for this contest, didn't implement the fix, and if deployed for this Notional Update will have the [bug](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/trading/TradingUtils.sol#L143C1-L151C10).**

Thereby making this submission valid.

**Comment by shealtielanz** [comment]
Same as the issue in #77
- High, as per past contest's risk rating - https://github.com/sherlock-audit/2022-12-notional-judging/issues/17

The issue was found in the  StableMath. library of the past contest however the library given for this contest still contained the bug.

**Comment by nevillehuang** [comment]
@jeffywu Can you take a look at this just to confirm? It seems the fix was implemented on the buy token side but the watson is having some confusion that no fix is implemented.

**Comment by nevillehuang** [comment]
@shealtielanz 

There is some confusion between `executeInternal()` and `executeTrade()`, which uses `_needsToUnwrapExcessWETH()` that correctly checks the sellToken [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingUtils.sol#L90), so this is a non-issue.

**Comment by shealtielanz** [comment]
Hello @nevillehuang 
You are correct on this, thanks for the clarification.

I believe the escalation can be rejected.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

Thank you @nevillehuang for driving the discussion here. Also appreciate @shealtielanz's comment on the final consensus.

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [shealtielanz](https://github.com/sherlock-audit/2023-10-notional-judging/issues/38/#issuecomment-1839014950): rejected
