### ISSUE TITLE
AuditorPraise - Execution of trades on external exchanges will fail whenever ETH is `buyToken` because TradingModule.sol contract lacks a payable fallback/receive function hence it won’t be able to receive ETH sent back from the dexes during the execution of trades.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#4]
AuditorPraise

high

# Execution of trades on external exchanges will fail whenever ETH is `buyToken` because TradingModule.sol contract lacks a payable fallback/receive function hence it won’t be able to receive ETH sent back from the dexes during the execution of trades.

## Summary
the TradingModule.sol contract lacks a payable fallback/receive function
## Vulnerability Detail
A payable fallback function is needed for handling transactions that are sent to the contract without specifying a particular function to call.

A payable receive function is also needed for a contract to be able to handle incoming ETH. 

Whenever dexes are sending back the ETH bought during the execution of trades, The TradingModule.sol contract won't be able to receive it because it lacks a payable fallback/receive function.

Vaults won't be able to execute trades on external exchanges via the trading module whenever ETH is the primary token (i.e buyToken).

## Impact
Vaults won't be able to execute trades on external exchanges via the trading module whenever ETH is the primary token (i.e buyToken).

## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingModule.sol#L23
## Tool used

Manual Review

## Recommendation
Add a payable fallback/receive function to TradingModule.sol

**Comment by jeffywu** [comment]
Invalid, trades are executed via `delegatecall` context and BaseStrategyVault has a payable fallback.
