### ISSUE TITLE
Bauer - Potential Stranded Rewards in Aura Pool for Newly Added Tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#50]
Bauer

high

# Potential Stranded Rewards in Aura Pool for Newly Added Tokens

## Summary
The introduction of new rewards to the Aura pool may result in the tokens becoming stranded within the protocol, rendering them inaccessible for withdrawal.
## Vulnerability Detail
If a new reward token is added to the [Aura pool](https://etherscan.io/address/0xfb6b1c1a1ea5618b3cfc20f81a11a97e930fa46b#code), calling `getReward()` will introduce the new reward token into the protocol. However, when the `REWARD_REINVESTMENT_ROLE` executes `reinvestReward()`, there is a check in `_isInvalidRewardToken()` that verifies the token against the ones specified during initialization. 
```solidity
function _isInvalidRewardToken(address token) internal override view returns (bool) {
        return (
            token == TOKEN_1 ||
            token == TOKEN_2 ||
            token == TOKEN_3 ||
            token == TOKEN_4 ||
            token == TOKEN_5 ||
            token == address(AURA_BOOSTER) ||
            token == address(AURA_REWARD_POOL) ||
            token == address(Deployments.WETH)
        );
    }

```

Since the newly added reward token is not part of the initial specification, the validation fails. As a result, the token cannot be exchanged for pool tokens and cannot be withdrawn, remaining indefinitely within the protocol.

## Impact
The introduction of new rewards to the Aura pool may result in the tokens becoming stranded within the protocol。
## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L385-L411

## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid,  rewardToken is specified during Aura pool creation and cannot be changed after

**Comment by jeffywu** [comment]
Invalid, agree with @nevillehuang

**Comment by sleepriverfish** [comment]
Escalate

The `rewardManager` has the capability to invoke the function `addExtraReward()`, allowing the addition of a new rewardToken.
https://etherscan.io/address/0x1204f5060be8b716f5a62b4df4ce32acd01a69f5#writeContract
The problem described [here](https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/127) is also related to the issue caused by adding reward tokens.

**Comment by sherlock-admin2** [comment]
> Escalate
> The `rewardManager` has the capability to invoke the function `addExtraReward()`, allowing the addition of a new rewardToken.
> https://etherscan.io/address/0x1204f5060be8b716f5a62b4df4ce32acd01a69f5#writeContract
> The problem described [here](https://github.com/sherlock-audit/2023-04-blueberry-judging/issues/127) is also related to the issue caused by adding reward tokens.

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).
