### ISSUE TITLE
Im_th3AK - Setter function does not use function parameters and hardcodes the storage slot

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#54]
Im_th3AK

high

# Setter function does not use function parameters and hardcodes the storage slot

## Severity
- High
## Summary
The function `VaultStorage.setStrategyVaultState(StrategyVaultState)` in the file `VaultStorage.sol` is a setter function that does not use the function parameters and hardcodes the storage slot to zero. This violates the best practices for writing smart contracts and introduces a potential vulnerability.
## Vulnerability Detail
A setter function is a function that is used to modify the state of a contract by writing to its storage variables. A setter function should use the function parameters to pass the new values for the storage variables. However, the function `VaultStorage.setStrategyVaultState(StrategyVaultState)` does not do this. Instead, it takes a `StrategyVaultState` struct as a parameter, but does not use it to update the storage variables. Instead, it uses a mapping called `store` to access the storage slot zero and assigns the parameter value to it. This means that the function always writes to the same storage slot, regardless of the parameter value. This is a strange and risky behavior, as it could overwrite the existing state of the contract or cause unexpected side effects.
## Impact
The impact of this vulnerability depends on how the function `VaultStorage.setStrategyVaultState(StrategyVaultState)` is used and what the `StrategyVaultState` struct contains. If the function is called by other functions in the contract or by external users, it could lead to inconsistent or incorrect state updates. For example, if the `StrategyVaultState` struct contains information about the vault’s strategy, such as the address, the balance, the fees, etc., then the function could overwrite the existing strategy with a new one, without checking the validity or the compatibility of the new strategy. This could result in loss of funds, unauthorized transfers, incorrect fee calculations, etc. Alternatively, if the function is never called or the `StrategyVaultState` struct is irrelevant, then the function is redundant and wastes gas.
## Code Snippet

Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/VaultStorage.sol#L62-L66
```solidity
function setStrategyVaultState(StrategyVaultState memory state) internal {
    mapping(uint256 => StrategyVaultState) storage store = _state();
    // Hardcode to the zero slot
    store[0] = state;
}

```
## Tool used

- Manual Review

## Recommendation
The recommendation to fix this vulnerability is to make sure that the setter function actually sets something. This can be done by either using the function parameters to update the storage variables, or by removing the function altogether if it is not needed. For example, a possible fix could be:
```solidity
function setStrategyVaultState(StrategyVaultState memory state) internal {
    // Use the function parameter to update the storage variables
    _strategyVaultState = state;
}

```

## Same Issue But Different Location 
Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/VaultStorage.sol#L41-L51

## Code Snippet

```solidity
function setStrategyVaultSettings(StrategyVaultSettings memory settings) internal {
    // Check limits
    require(settings.maxPoolShare <= Constants.VAULT_PERCENT_BASIS);
    require(settings.oraclePriceDeviationLimitPercent <= Constants.VAULT_PERCENT_BASIS);

    mapping(uint256 => StrategyVaultSettings) storage store = _settings();
    // Hardcode to the zero slot
    store[0] = settings;

    emit StrategyVaultSettingsUpdated(settings);
}
 ```
## Recommendation

```solidity
function setStrategyVaultSettings(StrategyVaultSettings memory settings) internal {
    // Check limits
    require(settings.maxPoolShare <= Constants.VAULT_PERCENT_BASIS);
    require(settings.oraclePriceDeviationLimitPercent <= Constants.VAULT_PERCENT_BASIS);

    // Use the function parameter to update the storage variable
    _strategyVaultSettings = settings;

    emit StrategyVaultSettingsUpdated(settings);
}

```

**Comment by nevillehuang** [comment]
Invalid, storage variables correctly updated with assigned storage slot `STRATEGY_VAULT_SETTINGS_SLOT` to store vault settings and `STRATEGY_VAULT_STATE_SLOT` to store vault state
