### ISSUE TITLE
Im_th3AK - Unprotected call to a function sending Ether to an arbitrary address.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#55]
Im_th3AK

high

# Unprotected call to a function sending Ether to an arbitrary address.

## Summary

The function `CrossCurrencyVault._depositFromNotional(address,uint256,uint256,bytes)` in the file `CrossCurrencyVault.sol` is a function that sends Ether to an arbitrary address without proper checks. This violates the best practices for writing secure smart contracts and introduces a potential vulnerability.

## Vulnerability Detail

A function that sends Ether to an arbitrary address should be protected by modifiers or require statements that ensure that only authorized users can withdraw funds. However, the function `CrossCurrencyVault._depositFromNotional(address,uint256,uint256,bytes)` does not do this. Instead, it calls the `WETH.deposit{value: lendUnderlyingTokens}()` function, which sends Ether to the address of the WETH contract. This function does not check the validity or the origin of the `lendUnderlyingTokens` parameter, which is derived from the data parameter of the function. This means that an attacker could pass malicious `data` to the function and cause it to send Ether to an arbitrary address. This is a dangerous and risky behavior, as it could result in loss of funds, unauthorized transfers, or denial of service.

## Impact

The impact of this vulnerability depends on how the function `CrossCurrencyVault._depositFromNotional(address,uint256,uint256,bytes)` is used and what the data parameter contains. If the function is called by other functions in the contract or by external users, it could lead to loss of funds, unauthorized transfers, or denial of service. For example, an attacker could pass data that contains a large amount of `lendUnderlyingTokens` and a malicious `exchangeData` that causes the `_executeTrade` function to fail. This would result in the function sending Ether to the WETH contract without receiving any tokens in return. Alternatively, an attacker could pass data that contains a small amount of `lendUnderlyingTokens` and a malicious `exchangeData` that causes the `_executeTrade` function to succeed. This would result in the function sending Ether to the `WETH` contract and receiving tokens in return, but the tokens would be sent to an arbitrary address specified by the attacker. This would result in the function losing control of the tokens and the vault shares.

## Code Snippet

Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L161-L204
```solidity
function _depositFromNotional(
    address /* account */,
    uint256 depositUnderlyingExternal,
    uint256 maturity,
    bytes calldata data
) internal override returns (uint256 vaultShares) {
    if (depositUnderlyingExternal == 0) return 0;

    IERC20 lendToken = LEND_UNDERLYING_TOKEN;
    DepositParams memory params = abi.decode(data, (DepositParams));
    Trade memory trade = Trade({
        tradeType: TradeType.EXACT_IN_SINGLE,
        sellToken: address(_underlyingToken()),
        buyToken: address(lendToken),
        amount: depositUnderlyingExternal,
        limit: params.minPurchaseAmount,
        deadline: block.timestamp,
        exchangeData: params.exchangeData
    });

    // Executes a trade on the given Dex, the vault must have permissions set for
    // each dex and token it wants to sell. Each vault will only have permissions to
    // buy and sell the lend and borrow underlying tokens via specific dexes.
    (/* */, uint256 lendUnderlyingTokens) = _executeTrade(params.dexId, trade);
    bool isETH = LEND_ETH;

    if (maturity == Constants.PRIME_CASH_VAULT_MATURITY) {
        // Lend variable
        vaultShares = _depositToPrimeCash(isETH, lendUnderlyingTokens);
    } else {
        // Lending fixed, the fCash wrapper uses WETH instead of ETH.
        IWrappedfCash wfCash = getWrappedFCashAddress(maturity);
        if (isETH) {
            // Unprotected call to a function sending Ether to an arbitrary address
            WETH.deposit{value: lendUnderlyingTokens}();
            IERC20(address(WETH)).approve(address(wfCash), lendUnderlyingTokens);
        } else {
            lendToken.approve(address(wfCash), lendUnderlyingTokens);
        }
        vaultShares = wfCash.deposit(lendUnderlyingTokens, address(this));
    }

    // Slippage check against lending
    require(params.minVaultShares <= vaultShares, "Slippage: Vault Shares");
}

```
## Tool used

- Manual Review

## Recommendation

The recommendation to fix this vulnerability is to ensure that an arbitrary user cannot withdraw unauthorized funds. This can be done by adding modifiers or require statements that check the validity and the origin of the data parameter and the `lendUnderlyingTokens` parameter.
```solidity
function _depositFromNotional(
    address account,
    uint256 depositUnderlyingExternal,
    uint256 maturity,
    bytes calldata data
) internal override returns (uint256 vaultShares) {
    if (depositUnderlyingExternal == 0) return 0;

    IERC20 lendToken = LEND_UNDERLYING_TOKEN;
    DepositParams memory params = abi.decode(data, (DepositParams));
    Trade memory trade = Trade({
        tradeType: TradeType.EXACT_IN_SINGLE,
        sellToken: address(_underlyingToken()),
        buyToken: address(lendToken),
        amount: depositUnderlyingExternal,
        limit: params.minPurchaseAmount,
        deadline: block.timestamp,
        exchangeData: params.exchangeData
    });

    // Executes a trade on the given Dex, the vault must have permissions set for
    // each dex and token it wants to sell. Each vault will only have permissions to
    // buy and sell the lend and borrow underlying tokens via specific dexes.
    (/* */, uint256 lendUnderlyingTokens) = _executeTrade(params.dexId, trade);
    bool isETH = LEND_ETH;

    if (maturity == Constants.PRIME_CASH_VAULT_MATURITY) {
        // Lend variable
        vaultShares = _depositToPrimeCash(isETH, lendUnderlyingTokens);
    } else {
        // Lending fixed, the fCash wrapper uses WETH instead of ETH.
        IWrappedfCash wfCash = getWrappedFCashAddress(maturity);
        if (isETH) {
            // Check that the account is the sender of the Ether
            require(msg.value == lendUnderlyingTokens, "Invalid value");
            require(account == msg.sender, "Unauthorized sender");
            WETH.deposit{value: lendUnderlyingTokens}();
            IERC20(address(WETH)).approve(address(wfCash), lendUnderlyingTokens);
        } else {
            lendToken.approve(address(wfCash), lendUnderlyingTokens);
        }
        vaultShares = wfCash.deposit(lendUnderlyingTokens, address(this));
    }

    // Slippage check against lending
    require(params.minVaultShares <= vaultShares, "Slippage: Vault Shares");
}

```

**Comment by nevillehuang** [comment]
Invalid, access control on an internal function doesn't make sense and proper access control is already implemented in the BaseStrategyVault [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/BaseStrategyVault.sol#L171)
