### ISSUE TITLE
Im_th3AK - Unprotected initializer function that approves unlimited allowance

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#56]
Im_th3AK

high

# Unprotected initializer function that approves unlimited allowance

## Summary
The function `ConvexStakingMixin._initialApproveTokens()` in the file `ConvexStakingMixin.sol` is an initializer function that does not have any protection. This violates the best practices for writing secure smart contracts and introduces a potential vulnerability. This vulnerability could lead to loss of funds, unauthorized transfers, or denial of service.
## Vulnerability Detail
An initializer function is a function that is used to initialize the state of a contract or a `mixin`. An initializer function should have modifiers or require statements that ensure that it can only be called once and by the owner of the contract or the `mixin`. However, the function `ConvexStakingMixin._initialApproveTokens()` does not have any protection. Instead, it calls the `checkApprove` function on three different tokens, which grants unlimited allowance to the `CURVE_POOL` and the `CONVEX_BOOSTER` contracts. This means that anyone can call this function multiple times and cause the contract to approve more tokens than necessary. This is a dangerous and risky behavior, as it could result in loss of funds, unauthorized transfers, or denial of service.
## Impact
The impact of this vulnerability depends on how the function `ConvexStakingMixin._initialApproveTokens()` is used and what the `CURVE_POOL` and the `CONVEX_BOOSTER` contracts do. If the function is called by other functions in the contract or by external users, it could lead to loss of funds, unauthorized transfers, or denial of service. For example, an attacker could call this function repeatedly and cause the contract to approve more tokens than it has. Then, the attacker could use the `CURVE_POOL` or the `CONVEX_BOOSTER` contracts to transfer the tokens from the contract to their own address. Alternatively, an attacker could call this function and cause the contract to approve more tokens than the `CURVE_POOL` or the `CONVEX_BOOSTER` contracts can handle. Then, the attacker could use the `CURVE_POOL` or the `CONVEX_BOOSTER` contracts to trigger an overflow or an underflow error and cause the contract to revert or fail.
## Code Snippet
Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/curve/ConvexStakingMixin.sol#L53-L58
## Tool used

- Manual Review

## Recommendation
The recommendation to fix this vulnerability is to protect the initializer function with modifiers or require statements. This can be done by using the `initializer` modifier from the OpenZeppelin library, or by using a custom modifier or a require statement that checks a `boolean` variable that indicates whether the function has been called before.
```solidity
// Using the initializer modifier from OpenZeppelin
function _initialApproveTokens() internal override initializer {
    // If either token is Deployments.ETH_ADDRESS the check approve will short circuit
    IERC20(TOKEN_1).checkApprove(address(CURVE_POOL), type(uint256).max);
    IERC20(TOKEN_2).checkApprove(address(CURVE_POOL), type(uint256).max);
    CURVE_POOL_TOKEN.checkApprove(address(CONVEX_BOOSTER), type(uint256).max);
}

// Using a custom modifier
modifier onlyOnce() {
    require(!_initialized, "Already initialized");
    _;
    _initialized = true;
}

bool private _initialized;

function _initialApproveTokens() internal override onlyOnce {
    // If either token is Deployments.ETH_ADDRESS the check approve will short circuit
    IERC20(TOKEN_1).checkApprove(address(CURVE_POOL), type(uint256).max);
    IERC20(TOKEN_2).checkApprove(address(CURVE_POOL), type(uint256).max);
    CURVE_POOL_TOKEN.checkApprove(address(CONVEX_BOOSTER), type(uint256).max);
}

// Using a require statement
bool private _initialized;

function _initialApproveTokens() internal override {
    require(!_initialized, "Already initialized");
    // If either token is Deployments.ETH_ADDRESS the check approve will short circuit
    IERC20(TOKEN_1).checkApprove(address(CURVE_POOL), type(uint256).max);
    IERC20(TOKEN_2).checkApprove(address(CURVE_POOL), type(uint256).max);
    CURVE_POOL_TOKEN.checkApprove(address(CONVEX_BOOSTER), type(uint256).max);
    _initialized = true;
}

```

**Comment by nevillehuang** [comment]
Invalid, `_initialApproveTokens()` is an internal function only called in `SingleSidedLPVaultBase.initialize()`, which is protected by an existing access control modifier `onlyNotionalOwner()` [here](https://github.com/sherlock-audit/2023-10-notional/blob/7aadd254da5f645a7e1b718e7f9128f845e10f02/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L173)
