### ISSUE TITLE
Im_th3AK - Uninitialized local variable in constructor.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#57]
Im_th3AK

medium

# Uninitialized local variable in constructor.

## Summary
The constructor of the `ConvexStakingMixin` contract in the file `ConvexStakingMixin.sol` declares a local variables `convexBooster` and `poolId` that is never initialized. This violates the best practices for writing secure smart contracts and introduces a potential vulnerability.
## Vulnerability Detail
A local variable is a variable that is declared and used within a function. A local variable should be initialized with a value before it is used, otherwise it will have an undefined value. However, the constructor of the `ConvexStakingMixin` contract does not initialize the local variables `convexBooster` and  `poolId`. Instead, it declares it as a `uint256` type and leaves it uninitialized. This means that the variables `convexBooster` and  `poolId` could have any value, depending on the state of the memory or the stack. This is a dangerous and risky behavior, as it could result in unexpected or incorrect behavior of the contract.
## Impact
The impact of this vulnerability depends on how the variables `convexBooster` and `poolId` are used and what it represents. If the variables `convexBooster` and `poolId` are used to store or access the pool id of the Convex staking contract, then it could lead to incorrect or invalid staking operations. For example, if the variables `convexBooster` and `poolId` have a random value that does not correspond to any existing pool id, then the contract could fail to stake or `unstake` the tokens, or stake or `unstake` the wrong tokens. Alternatively, if the variables `convexBooster` and `poolId` are not used at all, then it is redundant and wastes gas.
## Code Snippet
Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/curve/ConvexStakingMixin.sol#L31-L32
## Tool used

- Manual Review

## Recommendation
The recommendation to fix this vulnerability is to initialize all the local variables. If a variable is meant to be initialized to zero, explicitly set it to zero to improve code readability.
```diff
-    address convexBooster;
-    uint256 poolId;
+   address convexBooster = 0;
+   uint256 poolId = 0;
```

**Comment by nevillehuang** [comment]
Invalid, solidity automatically assigns default values even if not explicitly initialized with values
