### ISSUE TITLE
Im_th3AK - Ignored return value of an external function call

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#58]
Im_th3AK

medium

# Ignored return value of an external function call

## Summary
The function `BaseStrategyVault.deleverageAccount(address,address,address,uint16,int256)` in the file `BaseStrategyVault.sol` is a function that ignores the return value of an external call to the `NOTIONAL.deleverageAccount` function. This violates the best practices for writing secure smart contracts and introduces a potential vulnerability.
## Vulnerability Detail
A function that calls an external function should store the return value of the external function in a local or state variable. This allows the function to check the return value for errors or use it for further logic. However, the function `BaseStrategyVault.deleverageAccount(address,address,address,uint16,int256)` does not do this. Instead, it calls the `NOTIONAL.deleverageAccount` function with the value parameter set to `msg.value` and returns the return value directly. This means that the function does not check the return value for errors or use it for further logic. This is a dangerous and risky behavior, as it could result in unexpected or incorrect behavior of the contract.
## Impact
The impact of this vulnerability depends on how the function `BaseStrategyVault.deleverageAccount(address,address,address,uint16,int256)` is used and what the `NOTIONAL.deleverageAccount` function does. If the function is called by other functions in the contract or by external users, it could lead to unexpected or incorrect behavior of the contract. For example, if the `NOTIONAL.deleverageAccount` function returns an error code or a `zero` value, then the function could fail to deleverage the account or return a wrong value. Alternatively, if the `NOTIONAL.deleverageAccount` function returns a non-zero value, then the function could succeed to deleverage the account or return a correct value, but the function could miss the opportunity to use the return value for further logic, such as updating the state variables or emitting events.
## Code Snippet
Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/BaseStrategyVault.sol#L217-L229
## Tool used

- Manual Review

## Recommendation
The recommendation to fix this vulnerability is to ensure that all the return values of the external function calls are used. This can be done by storing the return value of the `NOTIONAL.deleverageAccount` function in a local variable and checking it for errors or using it for further logic. 
```solidity
function deleverageAccount(
    address account,
    address vault,
    address liquidator,
    uint16 currencyIndex,
    int256 depositUnderlyingInternal
) external payable returns (uint256 vaultSharesFromLiquidation, int256 depositAmountPrimeCash) {
    require(msg.sender == liquidator);
    _checkReentrancyContext();
    // Stores the return value of an external call in a local variable
    (vaultSharesFromLiquidation, depositAmountPrimeCash) = NOTIONAL.deleverageAccount{value: msg.value}(
        account, vault, liquidator, currencyIndex, depositUnderlyingInternal
    );
    // Checks the return value for errors or uses it for further logic
    require(vaultSharesFromLiquidation > 0, "Deleveraging failed");
    emit Deleveraged(account, vault, liquidator, vaultSharesFromLiquidation, depositAmountPrimeCash);
    return (vaultSharesFromLiquidation, depositAmountPrimeCash);
}

```

**Comment by nevillehuang** [comment]
Invalid, out of scope, this involves an out of scope function within the `NOTIONAL` contract.
