### ISSUE TITLE
AuditorPraise - if `isSingleSided` bool is false, execution of trades back to the primary token on external exchanges will fail due to non-transfer of the balance of the other tokens to be  sold for primary token into the trading Module

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#6]
AuditorPraise

high

# if `isSingleSided` bool is false, execution of trades back to the primary token on external exchanges will fail due to non-transfer of the balance of the other tokens to be  sold for primary token into the trading Module

## Summary
 the balance of the other tokens to be sold for primary token is never transferred into the trading module, hence trading module has nothing to trade with.
## Vulnerability Detail
`SingleSidedLPVaultBase._redeemFromNotional()` uses `StrategyUtils.executeRedemptionTrade()` to execute redemption trades whenever `isSingleSided` bool is false

Now the issue is that the balance of the other tokens to be sold for primary token is never transferred into the trading module, so the trading module has no funds to trade with on the external exchanges.

Here's the flow of a redemption trade:
- `BaseStrategyVault.redeemFromNotional()` calls `SingleSidedLPVaultBase._redeemFromNotional()` [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/BaseStrategyVault.sol#L183)

- `SingleSidedLPVaultBase._redeemFromNotional()` uses `StrategyUtils.executeRedemptionTrades` for execution of trades on external exchanges [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L278-L283)

- `StrategyUtils.executeRedemptionTrades` calls `_executeDynamicSlippageTradeExactIn()` [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L80)

- `_executeDynamicSlippageTradeExactIn()` makes the call to `TradeHandler._executeTrade()` [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/StrategyUtils.sol#L144)

- The main issue lies here in the `TradeHandler._executeTrade()`. 
The `TradeHandler._executeTrade()` just makes a delegate call to the  trading module without transferring the amount of sellToken to trade into the trading module.

## Impact
if `isSingleSided` bool is false, execution of trades back to the primary token on external exchanges will fail due to non-transfer of the balance of the other tokens to be sold for primary token into the trading Module 

 `SingleSidedLPVaultBase._redeemFromNotional()` will always revert due to lack of funds to execute trades on trading module as the funds were never transferred into the trading module.
## Tool used

Manual Review

## Recommendation
Have the vaults transfer amount of sellToken to execute trades with into the TradingModule.sol.

**Comment by jeffywu** [comment]
Invalid, TradingModule is executed via delegatecall context.
