### ISSUE TITLE
Im_th3AK - Dubious typecast from int256 to uint256 that can cause overflow or underflow.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#61]
Im_th3AK

medium

# Dubious typecast from int256 to uint256 that can cause overflow or underflow.

## Summary

The function `SingleSidedLPVaultBase._mintVaultShares(uint256)` in the file `SingleSidedLPVaultBase.sol` is a function that uses a dubious typecast from `int256` to `uint256`. This violates the best practices for writing secure smart contracts and introduces a potential vulnerability.
## Vulnerability Detail

A function that performs arithmetic operations on integers should be careful about the type and the sign of the operands and the result. Solidity’s typecast operator converts a value from one type to another, but it does not check the validity or the range of the conversion. However, the function `SingleSidedLPVaultBase._mintVaultShares(uint256)` does not take this into account. Instead, it uses a typecast from `int256` to `uint256` on the `constant Constants.INTERNAL_TOKEN_PRECISION`, which is defined as `-8`. This means that the function converts a negative value to an unsigned type, which could result in an overflow or an underflow. This is a dubious and risky behavior, as it could affect the calculation of the vault shares and the balance of the vault.
## Impact

The impact of this vulnerability depends on how the function `SingleSidedLPVaultBase._mintVaultShares(uint256)` is used and what the input parameter represents. If the function is used to mint vault shares for the LP tokens, then it could lead to incorrect or invalid minting operations. For example, if the function performs a typecast that causes an overflow or an underflow, then the function could mint more or less vault shares than expected. This could result in loss of funds, unauthorized transfers, or incorrect fee calculations.
## Code Snippet

Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L229-L249
```solidity
function _mintVaultShares(uint256 lpTokens) internal returns (uint256 vaultShares) {
    StrategyVaultState memory state = VaultStorage.getStrategyVaultState();
    if (state.totalPoolClaim == 0) {
        // Vault Shares are in 8 decimal precision
        // Uses a dubious typecast from int256 to uint256
        vaultShares = (lpTokens * uint256(Constants.INTERNAL_TOKEN_PRECISION)) / POOL_PRECISION();
    } else {
        vaultShares = (lpTokens * state.totalVaultSharesGlobal) / state.totalPoolClaim;
    }

    // Updates internal storage here
    state.totalPoolClaim += lpTokens;
    state.totalVaultSharesGlobal += vaultShares.toUint80();
    state.setStrategyVaultState();

    // Checks that the vault does not own too large of a portion of the pool. If this is the case,
    // single sided exits may have a detrimental effect on the liquidity.
    uint256 maxPoolShare = VaultStorage.getStrategyVaultSettings().maxPoolShare;
    uint256 maxSupplyThreshold = (_totalPoolSupply() * maxPoolShare) / Constants.VAULT_PERCENT_BASIS;
    if (maxSupplyThreshold < state.totalPoolClaim)
        revert Errors.PoolShareTooHigh(state.totalPoolClaim, maxSupplyThreshold);
}

```
## Tool used

- Manual Review

## Recommendation
The recommendation to fix this vulnerability is to use clear constants that match the type and the sign of the operands and the result. This can avoid the need for typecasting and improve the readability of the code. 
```solidity
function _mintVaultShares(uint256 lpTokens) internal returns (uint256 vaultShares) {
    StrategyVaultState memory state = VaultStorage.getStrategyVaultState();
    if (state.totalPoolClaim == 0) {
        // Vault Shares are in 8 decimal precision
        // Uses a clear constant that matches the type and the sign
        vaultShares = (lpTokens * Constants.VAULT_SHARES_PRECISION) / POOL_PRECISION();
    } else {
        vaultShares = (lpTokens * state.totalVaultSharesGlobal) / state.totalPoolClaim;
    }

    // Updates internal storage here
    state.totalPoolClaim += lpTokens;
    state.totalVaultSharesGlobal += vaultShares.toUint80();
    state.setStrategyVaultState();

    // Checks that the vault does not own too large of a portion of the pool. If this is the case,
    // single sided exits may have a detrimental effect on the liquidity.
    uint256 maxPoolShare = VaultStorage.getStrategyVaultSettings().maxPoolShare;
    uint256 maxSupplyThreshold = (_totalPoolSupply() * maxPoolShare) / Constants.VAULT_PERCENT_BASIS;
    if (maxSupplyThreshold < state.totalPoolClaim)
        revert Errors.PoolShareTooHigh(state.totalPoolClaim, maxSupplyThreshold);
}

```

**Comment by nevillehuang** [comment]
Invalid, in Constants.sol, `INTERNAL_TOKEN_PRECISION` is a constant assigned as 1e8 [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/global/Constants.sol#L10), which is always positive so no issue here when typecasting from int to uint
