### ISSUE TITLE
Im_th3AK - Missing event emission in setter function that updates the state of the vault.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#62]
Im_th3AK

medium

# Missing event emission in setter function that updates the state of the vault.

## Summary

The setter function `VaultStorage.setStrategyVaultState(StrategyVaultState)` in the file `VaultStorage.sol` is a function that does not emit an event when it updates the state of the vault. This violates the best practices for writing secure smart contracts and introduces a potential vulnerability.
## Vulnerability Detail

A setter function is a function that modifies the state of a contract or a variable. A setter function should emit an event that logs the changes and the parameters of the function. This allows the users and the developers to monitor the state of the contract and verify the correctness of the function. However, the setter function `VaultStorage.setStrategyVaultState(StrategyVaultState)` does not do this. Instead, it updates the state of the vault without emitting any event. This means that the users and the developers cannot track the changes and the parameters of the function. This is a dangerous and risky behavior, as it could result in inconsistency, ambiguity, or manipulation of the state of the vault.
## Impact

The impact of this vulnerability depends on how the setter function `VaultStorage.setStrategyVaultState(StrategyVaultState)` is used and what the state of the vault represents. If the setter function is used to update the strategy vault state, which contains information such as the total pool claim, the total vault shares, and the leverage ratio, then it could lead to inconsistency, ambiguity, or manipulation of the state of the vault. For example, if the setter function updates the state of the vault without emitting an event, then the users and the developers cannot verify the accuracy or the validity of the state of the vault. This could result in loss of funds, unauthorized transfers, or incorrect fee calculations.
## Code Snippet

Source Link:- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/VaultStorage.sol#L62-L66
```solidity
function setStrategyVaultState(StrategyVaultState memory state) internal {
    mapping(uint256 => StrategyVaultState) storage store = _state();
    // Hardcode to the zero slot
    store[0] = state;
    // Does not emit an event
}

```
## Tool used

- Manual Review

## Recommendation
The recommendation to fix this vulnerability is to emit an event in the setter function. This can be done by defining an event that contains the parameters of the function and the state of the vault, and emitting it after updating the state of the vault.
```solidity
// Define an event that logs the state of the vault
event StrategyVaultStateUpdated(
    uint256 totalPoolClaim,
    uint256 totalVaultSharesGlobal,
    uint256 leverageRatio
);

function setStrategyVaultState(StrategyVaultState memory state) internal {
    mapping(uint256 => StrategyVaultState) storage store = _state();
    // Hardcode to the zero slot
    store[0] = state;
    // Emit an event that logs the state of the vault
    emit StrategyVaultStateUpdated(
        state.totalPoolClaim,
        state.totalVaultSharesGlobal,
        state.leverageRatio
    );
}

```

**Comment by nevillehuang** [comment]
Informational finding, such event findings are not valid high/medium in sherlock since it does not directly impact the protocol.
