### ISSUE TITLE
Bauer - The protocol doesn't correctly account for AuraStash causing reward to be lost

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#66]
Bauer

high

# The protocol doesn't correctly account for AuraStash causing reward to be lost

## Summary
The protocol does not take into account the stash AURA rewards, which may result in this part of the rewards remaining in the protocol and unable to be withdrawn.

## Vulnerability Detail
Some Aura pools have two sources of AURA. First from the booster but also as a secondary reward. This secondary reward is stash AURA that doesn't behave like regular AURA. Although the protocol can obtain this part of the reward, it cannot be reinvested because the `_isInvalidRewardToken()` check will fail.
```solidity

  function reinvestReward(
        SingleSidedRewardTradeParams[] calldata trades,
        uint256 minPoolClaim
    ) external whenNotLocked onlyRole(REWARD_REINVESTMENT_ROLE) returns (
        address rewardToken,
        uint256 amountSold,
        uint256 poolClaimAmount
    ) {
        // Will revert if spot prices are not in line with the oracle values
        _checkPriceAndCalculateValue();

        // Require one trade per token, if we do not want to buy any tokens at a
        // given index then the amount should be set to zero. This applies to pool
        // tokens like in the ComposableStablePool.
        require(trades.length == NUM_TOKENS());
        uint256[] memory amounts;
        (rewardToken, amountSold, amounts) = _executeRewardTrades(trades);

        poolClaimAmount = _joinPoolAndStake(amounts, minPoolClaim);

        // Increase LP token amount without minting additional vault shares
        StrategyVaultState memory state = VaultStorage.getStrategyVaultState();
        state.totalPoolClaim += poolClaimAmount;
        state.setStrategyVaultState();

        emit RewardReinvested(rewardToken, amountSold, poolClaimAmount);
    }


```

## Impact
stash AURA rewards will remain in the protocol.

## Code Snippet
https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L385-L411

## Tool used

Manual Review

**Comment by jeffywu** [comment]
Can you provide more details on this reward and some example pools?

**Comment by nevillehuang** [comment]
Closing due to lack of details on example pools. IMO even if such pools exists, notional can always retrieve the rewards and opt to not reinvest anyways, and even that would be the trusted responsibility of admin with the Reward Reinvestment role

**Comment by sleepriverfish** [comment]
Escalate

[STASH AURA](https://docs.aura.finance/developers/deployed-addresses) is a valid `extraRewardToken`.
<img width="792" alt="86c45ac0-08cb-4526-a48c-85c0f626a25e" src="https://github.com/sherlock-audit/2023-10-notional-judging/assets/6247627/8c3f556d-050f-426f-9d92-d0d5626ebf98">

Here are two questions related to Stash reward tokens.
https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/632
https://github.com/sherlock-audit/2023-07-blueberry-judging/issues/108

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> [STASH AURA](https://docs.aura.finance/developers/deployed-addresses) is a valid `extraRewardToken`.
> <img width="792" alt="86c45ac0-08cb-4526-a48c-85c0f626a25e" src="https://github.com/sherlock-audit/2023-10-notional-judging/assets/6247627/8c3f556d-050f-426f-9d92-d0d5626ebf98">
> 
> Here are two questions related to Stash reward tokens.
> https://github.com/sherlock-audit/2023-06-tokemak-judging/issues/632
> https://github.com/sherlock-audit/2023-07-blueberry-judging/issues/108

The escalation could not be created because you are not exceeding the escalation threshold.

You can view the required number of additional valid issues/judging contest payouts in your Profile page,
in the [Sherlock webapp](https://app.sherlock.xyz/audits/).

**Comment by sleepriverfish** [comment]
Here is an example: [BaseRewardPool](https://etherscan.io/address/0x1204f5060bE8b716F5A62b4Df4cE32acD01a69f5#readContract)(https://etherscan.io/address/0x1204f5060bE8b716F5A62b4Df4cE32acD01a69f5#readContract)  has 1 extra reward -> [VirtualBalanceRewardPool](https://etherscan.io/address/0x503383F008AADC69b350c0e597C317630DedCE9D#readContract)(https://etherscan.io/address/0x503383F008AADC69b350c0e597C317630DedCE9D#readContract)， reward token is: (https://etherscan.io/address/0x8dDD55a18ad319Ffd25D09E057b25412eE511a09#readContract)[STASH_AURA](https://etherscan.io/address/0x8dDD55a18ad319Ffd25D09E057b25412eE511a09#readContract)
In the case of stash_aura,  the `getReward()` function calls the transfer on the stash_aura which will transfer the base asset, which in this case is aura in this case, not the stash_token itself. as you can see here
[https://etherscan.io/address/0x8dDD55a18ad319Ffd25D09E057b25412eE511a09#code#F1#L80](https://etherscan.io/address/0x8dDD55a18ad319Ffd25D09E057b25412eE511a09#code%23F1%23L80)

Therefore, the reward token is one of the pool tokens. This code ` if (_isInvalidRewardToken(rewardToken)) revert Errors.InvalidRewardToken(rewardToken);`  will fail, causing the protocol to be unable to reinvest AURA rewards.
