### ISSUE TITLE
shealtielanz - Incorrect check on the invariant

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-10-notional-judging#95]
shealtielanz

medium

# Incorrect check on the invariant

## Summary

`_redeemFromNotional()` in crossCurrency vault before withdrawing from Notional it does a check on the vault share where `            require(vaultShares <= type(uint88).max);` it checks against the max value of `unit88` instead of `uint80.max`

## Vulnerability Detail
```solidity 

function _redeemFromNotional(
        address /* account */,
        uint256 vaultShares,
        uint256 maturity,
        bytes calldata data
    ) internal override returns (uint256 borrowedCurrencyAmount) {
        if (vaultShares == 0) return 0;
        RedeemParams memory params = abi.decode(data, (RedeemParams));

        address lendToken = address(LEND_UNDERLYING_TOKEN);
        bool isETH = LEND_ETH;

        uint256 balanceBefore = TokenUtils.tokenBalance(lendToken);
        if (maturity == Constants.PRIME_CASH_VAULT_MATURITY) {
            // It should never be possible that this contract has a negative cash balance
@@>            require(vaultShares <= type(uint88).max);

            // Withdraws vault shares to underlying, will revert if the vault shares is
            // greater than the 
            NOTIONAL.withdraw(LEND_CURRENCY_ID, uint88(vaultShares), true);
        } else {
```

## Impact
In a scenario where the vault share is greater than uint80.max and less than uint88.max the contract will have a negative cash balance thereby breaking the invariant.
## Code Snippet
- https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L229
## Tool used

Manual Review

## Recommendation
```diff
-             require(vaultShares <= type(uint88).max);
+              require(vaultShares <= type(uint80).max);
```

**Comment by nevillehuang** [comment]
Invalid, there is no reason why `vaultShares` should be restricted to type(uint80).max
