### ISSUE TITLE
lemonmon - `TradingModule.getOraclePrice()` return values not checked inside `CrossCurrencyVault.convertStrategyToUnderlying()` which may lead to calculation issues or division by 0

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-10-notional-judging#98]
lemonmon

medium

# `TradingModule.getOraclePrice()` return values not checked inside `CrossCurrencyVault.convertStrategyToUnderlying()` which may lead to calculation issues or division by 0

## Summary

Inside `CrossCurrencyVault.sol` when `TradingModule.getOraclePrice()` is being called, the return values `answer` and `decimals` are not validated. If any of these return values are zero, a division by 0 may happen which causes a revert, additionally a multiplication by 0 may happen as well. In such a scenario, this may prevent the protocol from continuing operating.

## Vulnerability Detail

`TradingModule.getOraclePrice()` is returning `answer` which may be zero, since `answer` is calculated as `(basePrice * quoteDecimals * RATE_DECIMALS) / (quotePrice * baseDecimals);`, which may be truncated down to 0, depending on `basePrice` and `quotePrice`. Also the return value `decimals` may be 0, depending on future changes of the protocol source code, where it is stated that decimals are currently hardcoded to 1e18 (line 236 TradingModule.sol).

If `TradingModule.getOraclePrice()` returns `answer` or `decimals` with a value of 0,  calculations that are depending on these values may revert due to division by 0.

This issue was previously fixed:
- Inside `SingleSidedLPVaultBase._getOraclePairPrice()` where two require statements were implemented (line 324-325 SingleSidedLPVaultBase.sol) to address this issue.
- Inside `TradingModule.getLimitAmount()` line 290-291 where the require statements were adjusted from comparing `oraclePrice` and `oracleDecimals` with `> 0` instead of `>= 0` to disallow 0 values.

However this issue still exists inside `CrossCurrencyVault.sol`:

- `CrossCurrencyVault.convertStrategyToUnderlying()` is calling `TradingModule.getOraclePrice()` (line 131 CrossCurrencyVault.sol), but there are no require statements implemented to check the `rate` or `rateDecimals` return values not being 0. Then these values are used to calculate the return value (the value of the lent fCash in terms of the borrowed currency) as `(pvExternalUnderlying * borrowPrecision * rate) / (rateDecimals * lendPrecision)`. If `rateDecimals` is 0 then the calculation will revert due to division by 0, or the calculation returns 0 if `rate` is equal to 0.

A similar issue was reported in a previous audit [here](https://github.com/sherlock-audit/2022-12-notional-judging/issues/2)

## Impact

Whenever the value of the lent fCash in terms of the borrowed currency is calculated inside `CrossCurrencyVault` via `CrossCurrencyVault.convertStrategyToUnderlying()`, the calculation may either revert (division by 0) or return a wrong value which is calculated to be 0.

## Code Snippet

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/common/SingleSidedLPVaultBase.sol#L322-L327

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingModule.sol#L257-L260

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingModule.sol#L290-L291

https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/vaults/CrossCurrencyVault.sol#L131-L141

## Tool used

Manual Review

## Recommendation

Consider implementing the same validations into `CrossCurrencyVault.convertStrategyToUnderlying()`  as in `SingleSidedLPVaultBase._getOraclePairPrice()`:

```solidity
// CrossCurrencyVault.convertStrategyToUnderlying()

131        (int256 rate, int256 rateDecimals) = TRADING_MODULE.getOraclePrice(
132            address(LEND_UNDERLYING_TOKEN), address(underlyingToken)
133        );
+134        require(rate > 0);
+135        require(rateDecimals > 0);
```

**Comment by nevillehuang** [comment]
Invalid, decimals can never be zero as seen where decimals is always 1e18 assigned [here](https://github.com/sherlock-audit/2023-10-notional/blob/main/leveraged-vaults/contracts/trading/TradingModule.sol#L38)

`answer` or rate in this case can never be zero, since the quote currency between the oracles must match and since `basePrice` and `quotePrice` must both be greater than zero, `(basePrice * quoteDecimals * RATE_DECIMALS)` will never be smaller than `quotePrice * baseDecimals`.

**Comment by lemonmon1984** [comment]
Escalate
I think this issue should be valid if the lend and borrow tokens are not the same tokens.

`answer` can be zero if the `quotePrice` is bigger than `basePrice * RATE_DECIMALS`.
Here is an example where the `answer` is truncated down to 0:
`quotePrice ` = 20e18
`basePrice` = 10
`quoteDecimals` = 1e18
`baseDecimals` = 1e18
`answer = (basePrice * quoteDecimals * RATE_DECIMALS) / (quotePrice * baseDecimals)`
`answer = (10 * 1e18 * 1e18) / (20e18 * 1e18)`
`answer = (10 * 1e18) / 20e18; // quoteDecimals and baseDecimals cancel each other out`
`answer = 0` // truncated down to 0

Furthermore, about the question whether `decimals` can be 0. Here is the quote from the [previous finding](https://github.com/sherlock-audit/2022-12-notional-judging/issues/2):

> Additionally, decimals may in the future return zero, depending on changes to the protocol code, as [the NatSpec states that](https://github.com/notional-finance/leveraged-vaults/blob/dd797156651580737ba54506db075b9fdb3d35e9/contracts/trading/TradingModule.sol#L229) this is a number of decimals in the rate, currently hardcoded to 1e18 [2].

**Comment by sherlock-admin2** [comment]
> Escalate
> I think this issue should be valid if the lend and borrow tokens are not the same tokens.
> 
> `answer` can be zero if the `quotePrice` is bigger than `basePrice * RATE_DECIMALS`.
> Here is an example where the `answer` is truncated down to 0:
> `quotePrice ` = 20e18
> `basePrice` = 10
> `quoteDecimals` = 1e18
> `baseDecimals` = 1e18
> `answer = (basePrice * quoteDecimals * RATE_DECIMALS) / (quotePrice * baseDecimals)`
> `answer = (10 * 1e18 * 1e18) / (20e18 * 1e18)`
> `answer = (10 * 1e18) / 20e18; // quoteDecimals and baseDecimals cancel each other out`
> `answer = 0` // truncated down to 0
> 
> Furthermore, about the question whether `decimals` can be 0. Here is the quote from the [previous finding](https://github.com/sherlock-audit/2022-12-notional-judging/issues/2):
> 
> > Additionally, decimals may in the future return zero, depending on changes to the protocol code, as [the NatSpec states that](https://github.com/notional-finance/leveraged-vaults/blob/dd797156651580737ba54506db075b9fdb3d35e9/contracts/trading/TradingModule.sol#L229) this is a number of decimals in the rate, currently hardcoded to 1e18 [2].
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by nevillehuang** [comment]
@jeffywu Could you have a second look at this issue? 

Imo, such a small basePrice (10) seems not viable.

**Comment by jeffywu** [comment]
A base price of 10 in 1e18 decimals kind of absurd. The price is effectively zero. We want to revert if the price is zero, zero prices signify some sort of weird discontinuity.

**Comment by Czar102** [comment]
The submission does not present an impact that classifies as a loss of funds. A function returning "too small value" isn't necessarily a medium/high severity issue.

Secondly, it seems to be expected behavior determined by using `RATE_DECIMALS` precision. When any precision is chosen, there will always be an extreme price for which the rate will be zero. I think smart contracts are implicitly not compatible with tokens of such drastic difference in prices. Again, this doesn't mean any loss of funds unless explicitly noted in the submission.

Hence, I am planning to reject the escalation and leave the issue as is.

**Comment by nevillehuang** [comment]
Agree with @Czar102.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [lemonmon1984](https://github.com/sherlock-audit/2023-10-notional-judging/issues/98/#issuecomment-1840831119): rejected
